backend/modules/books/models/Books.php
<?php

namespace backend\modules\books\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%books}}".
 *
 * @property string $id
 * @property string $name
 * @property string $date_create
 * @property string $date_update
 * @property string $preview
 * @property integer $date
 * @property integer $author
 */
class Books extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $icon;
    public static function tableName()
    {
        return '{{%books}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_create',
                'updatedAtAttribute' => 'date_update',

            ],
        ];
    }
    public function rules()
    {
        return [
            [['date_create', 'date_update', 'author'], 'integer'],
            [['name'], 'string', 'max' => 250],
            [['date'], 'string', 'max' => 11],
            ['icon','file'                  ,
                'extensions'     =>'jpg, gif, png',
                'maxSize'   =>1024 * 1024 * 5,// 5 MB
                'skipOnEmpty'=>true,

            ],
        ];
    }



    public function getAuthors()
    {
        return $this->hasOne(Author::className(), ['id' => 'author']);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'date_create' => 'дата создания записи',
            'date_update' => 'дата обновления записи',
            'icon' => 'Картинка',
            'date' => 'дата выхода книги',
            'author' => ' ид автора в таблице авторы',
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
		$this->date = strtotime($this->date);

            return true;
        }
        return false;
    }
}

backend/modules/books/controllers/BooksController.php
<?php

namespace backend\modules\books\controllers;

use Yii;
use backend\modules\books\models\Books;
use backend\modules\books\models\BooksSeach;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * BooksController implements the CRUD actions for Books model.
 */
class BooksController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' =>[

                    [
                        'allow'   => true,
                        'roles'   => [ '@' ],
                    ],

                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

        ];
    }




    /**
     * Lists all Books models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BooksSeach();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        Url::remember();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Books model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Books model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Books();

        $model->icon = UploadedFile::getInstance($model, 'icon');


        if($model->icon) {
            $path = Yii::getAlias('@webroot') . '/images/' . $model->icon->baseName.'.'.$model->icon->extension;
            $model->icon->saveAs($path);
            $model->preview = Yii::getAlias('@web').'/images/' . $model->icon->baseName.'.'.$model->icon->extension;;


        }


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Books model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		
		$model->icon = UploadedFile::getInstance($model, 'icon');
        if($model->icon) {
            $path = Yii::getAlias('@webroot') . '/images/' . $model->icon->baseName.'.'.$model->icon->extension;
            $model->icon->saveAs($path);
            $model->preview = Yii::getAlias('@web').'/images/' . $model->icon->baseName.'.'.$model->icon->extension;;


        }
		
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect( Url::previous());
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Books model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Books model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Books the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Books::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/books/views/books/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \yii\helpers\ArrayHelper;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model backend\modules\books\models\Books */
/* @var $form yii\widgets\ActiveForm */
$model->date=date('d.m.Y',$model->date);
?>

<div class="books-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>



    <?= $form->field($model, 'icon')->fileInput(); ?>

<?= $form->field($model, 'date')->widget(DatePicker::className(), [


                       // 'value' => date('d.m.Y',$model->date_mer),
                        'language' => 'ru',

                        'options' => ['placeholder' => 'Select issue date ...'],
                        'pluginOptions' => [
                            'format' => 'dd.mm.yyyy',

                            'todayHighlight' => true
                        ]
                    ]); ?>

    <?= $form->field($model, 'author')->dropDownList(ArrayHelper::map(\backend\modules\books\models\Author::find()->all(),'id','lastname')); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/books/views/books/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model backend\modules\books\models\BooksSeach */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="books-search">
    <div class="col-lg-4">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>


<?php
echo '<span>Дата выхода книги:</span>';
echo DatePicker::widget([
    'name' => 'from_date',
    'value' => '',
    'type' => DatePicker::TYPE_RANGE,
    'name2' => 'to_date',
    'value2' => '',
    'pluginOptions' => [
        'autoclose'=>true,
        'format' => 'dd.mm.yyyy',
        'autoclose'=>true,
        'todayHighlight' => true
    ]
]);

?>
    <?= $form->field($model, 'name') ?>
    <?=$form->field($model, 'author')->dropDownList(ArrayHelper::map(\backend\modules\books\models\Author::find()->all(),'id','lastname'),['prompt' =>'Автор']); ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    </div>
</div>

backend/modules/books/views/books/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\books\models\Books */

$this->title = 'Create Books';
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/books/views/books/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use \yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>


<?
$this->title = 'Books';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-index">
	<?=$this->render('_search', ['model' => $searchModel]); ?>
	<div class="col-lg-12">
		<h1>
			<?= Html::encode($this->title) ?>
		</h1>

		<p>
			<?= Html::a('Create Books', ['create'], ['class' => 'btn btn-success']) ?>
		</p>
		<?php

		Modal::begin([
				'header' => ' Просмотр книги',
				'id' =>'modal',
				'size'=>'modal-lg'


			]);
		Modal::end();
		?>
		<?= GridView::widget([
				'dataProvider' => $dataProvider,
				// 'filterModel' => $searchModel,
				'columns' => [
					'id',
					'name',
					[
						'attribute' => 'preview',
						'format' => 'html',
						'value' =>
						function ($model)
						{
							return Html::a(Html::img($model->preview,['width' => '140px']),$model->preview,['class'=>'simple']);
						},
					],

					[
						'attribute' => 'authors',
						'value' =>
						function($model)
						{
							return $model->authors->firstname . ' ' . $model->authors->lastname;
						}
					],
					[
						'attribute' => 'date',
						'value' =>
						function($model)
						{
							if(!empty($model->date))
							return date('d.m.Y',$model->date);
						}
					],
					[
						'attribute' => 'date_create',
						'value' =>
						function($model)
						{

							return date('d.m.Y H:i:s',$model->date_create);
						}
					],
					[
						'attribute' => 'date_update',
						'value' =>
						function($model)
						{
							return date('d.m.Y H:i:s',$model->date_update);
						}
					],
					[
						'class' => \yii\grid\ActionColumn::className(),
						'buttons'=>[
							'view'=>
							function ($url,$model)
							{

								return Html::a('<span class="glyphicon glyphicon-eye-open"></span>','#',['value' => Url::to(['books/view','id'=>$model->id]),'id'=>'viewBookBtn']);
							}
						],
						'template'=>'{view}{update}{delete}',
					]
				],
			]); ?>
	</div>
</div>

backend/modules/books/views/books/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\books\models\Books */

$this->title = 'Update Books: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="books-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/books/views/books/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\books\models\Books */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-view">

	<h1>
		<?= Html::encode($this->title) ?>
	</h1>


	<?= DetailView::widget([
			'model' => $model,
			'attributes' => [
				'id',
				'name',
				[
					'attribute' => 'date_create',
					'value' => date('d.m.Y H:i:s',$model->date_create)

				],
				[
					'attribute' => 'date_update',
					'value' => date('d.m.Y H:i:s',$model->date_update)

				],
				[
					'attribute' => 'preview',
					'format' => 'html',
					'value' => Html::img($model->preview,['width' => '140px'])
				],
				[
					'attribute' => 'date',
					'value' => date('d.m.Y',$model->date)

				],
				[
					'attribute' => 'authors',
					'value' => $model->authors->firstname . ' ' . $model->authors->lastname,

				],
			],
		]) ?>

</div>